LIBFT_INCLUDES := inc/ft_arraylist.h \
				inc/ft_ctype.h \
				inc/ft_list.h \
				inc/ft_norm.h \
				inc/ft_parser.h \
				inc/ft_printers.h \
				inc/ft_stdio.h \
				inc/ft_stdlib.h \
				inc/ft_strbuff.h \
				inc/ft_string.h \
				inc/ft_stdbool.h